import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IntelliCode AI",
  description: "Generated by IntelliCode AI ⚡ AI Powered Code Explainer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-screen px-4 py-4  text-white bg-linear-to-br from-slate-950 via-slate-900 to-slate-950">

        {/* Glow background ONLY */}
        <div className=" fixed inset-0 -z-10">
          <div className="absolute -top-30 -left-30 w-100 h-100 bg-purple-300/20 blur-[120px] rounded-full" />
          <div className="absolute -bottom-30 -right-30 w-100 h-100 bg-cyan-200/20 blur-[120px] rounded-full" />
        </div>
        <AppProvider>
          {children}
        </AppProvider>

      </body>
    </html>
  );
}
